language: ruby
rvm:
- 2.3.3
before_install: ./install.sh
install: ./compile.sh
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
cache:
  directories:
  - node_modules
  - $HOME/.rvm
